modLoader="javafml"
loaderVersion="[61,)"
license="GNU GENERAL PUBLIC LICENSE"
#issueTrackerURL="https://github.com/MyOrganization/MyMod/" #optional
#clientSideOnly=true #optional, default=false

[[mods]]
modId="trowelanderror"
version="1.4.1"
displayName = "Trowel & Error"
#updateJSONURL="https://example.com/updates.json" #optional
#displayURL="https://example.com/" #optional
logoFile="trowelanderror.png" #optional
#credits="" #optional
authors="Emmery Chrisco" #optional
#displayTest="MATCH_VERSION" #optional, default=MATCH_VERSION when not clientSideOnly, else IGNORE_ALL_VERSION

description='''A new and up-to-date take on Torojima's
wonderful, but abandoned Buildhelper Wands mod.'''

[[dependencies.trowelanderror]] #recommended
    modId="forge"
    mandatory=true
    versionRange="[61,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.trowelanderror]] #recommended
    modId="minecraft"
    mandatory=true
    versionRange="[1.21.11,1.22,)"
    ordering="NONE"
    side="BOTH"